### ISSUE TITLE
Test shape of output from to_rna

### ISSUE THREAD

**Issue by wilhelm-now** [exercism/j#116]
Hi, I'm a beginner to J and tried the rna-transcription exercise. My first imperative attempt started with an empty string and did a while loop appending individual transcribed characters to the output.

```
transcribe =: monad : 0
out =. ''
select. y
case. 'G' do. out =. 'C'
case. 'C' do. out =. 'G'
case. 'T' do. out =. 'A'
case. 'A' do. out =. 'U'
end.
out
)

to_rna=: monad : 0
out =. ''
count =. # y
i =. 0
while. i < count do.
 out =. out , transcribe i { y
 i =. i + 1
end.
out
)
```

Visually this prints expected results but the shape is not preserved when the input is only one character.

```
   $ 'C'           NB. empty print is expected https://www.jsoftware.com/help/primer/shape.htm

   $ to_rna 'G'
1
```

It took me a while to understand that this is the reason tests 2, 3, 4, and 5 failed. Would it help if there was a test for preserving shape of input?

**Comment by ErikSchierboom** [comment]
@eNascimento178 Something for you to consider.

**Comment by eNascimento178** [comment]
I will choose the -:&, option for this case and, at a later moment, include a message in the analyser highlighting the issue with the shapes after the student creates the solution plus some hints If stuck.
